misc,tests: Wipe cache and attempt MacOS rebuild in Daily tests
As the environment is not fixed, there can be instances where the
cached MacOS build becomes incompatible with the currenty MacOS build
environment (for example, when a dependency version changes, the gem5
cached code built with the older version can't be used to build gem5
in an environemnt with the newer dependency version).

This is fixed by catching the compilation error and wiping the cached
content then trying again, building from scatch. If successful then
this newer version will replace the older cache.

diff --git a/.github/workflows/daily-tests.yaml b/.github/workflows/daily-tests.yaml
--- a/.github/workflows/daily-tests.yaml
+++ b/.github/workflows/daily-tests.yaml
@@ -58,8 +58,20 @@ jobs:
 
             - name: Compile gem5.${{ matrix.type }}
               working-directory: ${{ github.workspace }}
-              run: scons build/ALL/gem5.${{ matrix.type }} -j $(sysctl -n hw.ncpu)
-              timeout-minutes: 90
+              run: |
+                  CMD="scons build/ALL/gem5.${{ matrix.type }} -j $(sysctl -n hw.ncpu)"
+                  ${CMD}
+                  status=$?
+                  if [ $status -ne 0 ]; then
+                      echo "Failed to build on top of cached build." 1>&2
+                      echo "This may be due to env changes since the cache build." 1>&2
+                      echo "Clearing cache and attempting another build..." 1>&2
+                      rm -rf build
+                      ${CMD}
+                      status=$?
+                  fi
+                  exit $status
+              timeout-minutes: 120
 
     build-all-gem5:
         runs-on: [self-hosted, linux, x64]
